version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager
    restart: unless-stopped
    ports:
      - "8000:8000"  # Laravel port
      - "5173:5173"  # Vite dev server port
    volumes:
      - ./:/var/www/html
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      APP_ENV: local
    command: bash -c "chmod +x /var/www/html/start.sh && /var/www/html/start.sh"
